#!/usr/bin/env python3
"""Narrate what the harness controller does, when, and under which conditions.

Drives the mock bring-up from the outside — publishing exactly where a policy
would publish, reading exactly what a customer's ingest would read — and
prints a decoded, annotated timeline of every decision the gate makes.

    ros2 launch harness_controller harness_mock.launch.py     # terminal 1
    ros2 run harness_controller harness_flow.py               # terminal 2

Modes:
    (default)   guided walkthrough, one scenario at a time, Enter to advance
    --auto      run the whole walkthrough unattended (for CI / recording)
    --repl      type torque values and watch the gate respond

What it subscribes to. Three topics, deliberately different in kind:

  /harness_controller/info                harness_msgs/HarnessInfo
      Latched (transient-local), published once per activation: profile
      identity, the ordered joint names, the joint-order hash and the declared
      bounds. Every positional array below is indexed by that ordering, and
      reading them without it is a mistake no wire format can prevent.

  /harness_controller/gate_status         harness_msgs/GateStatus
      The OPERATIONAL view, one message per control cycle: decision, band,
      candidate and emitted. Says WHAT happened, in a form an integrator can
      wire into their own logic without decoding protobuf. `emitted` here is
      authoritative for what reached the actuator.

  /harness_controller/enforcement_events  harness_msgs/EnforcementEvents
      A TAP on the kernel's event ring — NOT the system of record, which is
      the MCAP episode written in-process. A self-describing envelope
      (schema + encoding) around varint-delimited harness.v1.EnforcementEvent
      protobufs. Says WHY: which predicate failed, the signed margin, sequence
      numbers, and how many events were dropped for want of ring space.

Enforcement itself appears on none of them. The gate runs on ros2_control's
command/state interfaces, in-process and synchronous with the update loop;
these topics describe it and never carry it. And the controller republishes
the event bytes without parsing them, so protobuf decoding never touches the
control loop — it happens out here, which is exactly the split intended.

Operational health also goes to /diagnostics as a DiagnosticArray, where a
customer's existing rqt_robot_monitor or aggregator picks it up for free.
"""

from __future__ import annotations

import argparse
import math
import os
import sys
import time
from dataclasses import dataclass, field

import rclpy
from harness_msgs.msg import EnforcementEvents, GateStatus, HarnessInfo
from rclpy.node import Node
from rclpy.qos import DurabilityPolicy, QoSProfile, ReliabilityPolicy
from std_msgs.msg import Float64MultiArray


def _load_generated_protobuf():
    """Import the committed harness.v1 Python bindings.

    Generated code is committed (schemas/README.md) and generated by the same
    protoc the C++ side uses, so the decoder here and the encoder in the
    kernel cannot drift apart without CI's codegen-drift gate noticing.
    """
    candidates = []
    env = os.environ.get("HARNESS_SCHEMAS_PY")
    if env:
        candidates.append(env)

    # Walk up from both the script and the working directory looking for
    # schemas/gen/python. A fixed number of ".." steps would only be right in
    # the source tree: installed (install/harness_controller/lib/
    # harness_controller/) the script sits at a completely different depth,
    # and with --symlink-install it sits at yet another.
    def _walk_up(start: str):
        current = os.path.abspath(start)
        while True:
            candidate = os.path.join(current, "schemas", "gen", "python")
            if os.path.isdir(candidate):
                return candidate
            parent = os.path.dirname(current)
            if parent == current:
                return None
            current = parent

    for start in (os.path.dirname(os.path.abspath(__file__)), os.getcwd()):
        found = _walk_up(start)
        if found:
            candidates.append(found)

    for path in candidates:
        if os.path.isdir(path) and path not in sys.path:
            sys.path.insert(0, path)
    try:
        from harness.v1 import enforcement_pb2  # noqa: WPS433 (deliberate late import)

        return enforcement_pb2
    except ImportError as exc:
        sys.exit(
            f"could not import harness.v1.enforcement_pb2 ({exc}).\n"
            f"Tried: {candidates}\n"
            "Set HARNESS_SCHEMAS_PY to <repo>/schemas/gen/python, and make sure "
            "'buf generate' has been run (scripts/regen_schemas_and_build_edge.sh)."
        )


pb = _load_generated_protobuf()

# ---------------------------------------------------------------------------
# Wire decoding
# ---------------------------------------------------------------------------

# Mirrors hk_decision / hk_band in edge/include/harness/harness_kernel.h.
# NOT the same numbering as harness.v1.Band on the wire, which carries an
# extra UNSPECIFIED=0 — see wire_band() in kernel_gate.cpp. Keeping both
# tables here rather than casting between them is the whole point.
DECISION_NAMES = {0: "ADMIT", 1: "CLAMP", 2: "HOLD_LAST", 3: "REJECT"}
BAND_NAMES = {0: "NOMINAL", 1: "BAND_A", 2: "BAND_B"}

_NOMINAL_MEANING = {
    "ADMIT": "candidate was inside every bound; it reached the actuator unchanged",
    "CLAMP": "candidate violated a bound and was replaced by the bound itself",
}

# In Band B the decision code means something different, and reading it with
# the nominal table is actively misleading: kernel_gate.cpp reports HK_CLAMP
# for an on_reject=ZERO fallback, so a a perfectly legal command shows up as
# "CLAMP" while what actually goes out is zero. Nothing was clamped to a
# bound — authority simply is not with the model any more.
_BAND_B_MEANING = {
    "CLAMP": "Band B fallback: emitting ZERO (profile on_reject=ZERO) — NOT a clamp to a bound",
    "REJECT": "Band B fallback: refusing to emit (on_reject=REJECT)",
    "HOLD_LAST": "Band B fallback: re-emitting the last admitted command (on_reject=HOLD_LAST)",
}


def decision_meaning(decision: str, band: str) -> str:
    if band == "BAND_B":
        return _BAND_B_MEANING.get(decision, "Band B fallback output")
    return _NOMINAL_MEANING.get(decision, "")


def read_varint(buf: bytes, pos: int) -> tuple[int, int]:
    """Decode one base-128 varint. Returns (value, next_pos)."""
    result = 0
    shift = 0
    while pos < len(buf):
        byte = buf[pos]
        pos += 1
        result |= (byte & 0x7F) << shift
        if not byte & 0x80:
            return result, pos
        shift += 7
        if shift > 63:
            raise ValueError("varint longer than 64 bits — buffer is not a valid event frame")
    raise ValueError("truncated varint at end of buffer")


def decode_events(raw: bytes) -> list:
    """Split one drained ring buffer into EnforcementEvents.

    Framing is written by try_write_event() in edge/src/kernel/event_sink.hpp:
    a varint byte-length followed by that many bytes of serialised
    harness.v1.EnforcementEvent, repeated until the buffer is consumed.
    """
    events = []
    pos = 0
    while pos < len(raw):
        length, pos = read_varint(raw, pos)
        chunk = raw[pos : pos + length]
        if len(chunk) < length:
            raise ValueError("truncated event body — drained fewer bytes than the prefix claims")
        pos += length
        event = pb.EnforcementEvent()
        event.ParseFromString(bytes(chunk))
        events.append(event)
    return events


def describe_projection(event) -> list[str]:
    """Render a ProjectionEvent the way a reviewer needs to read it."""
    proj = event.projection
    verdict = pb.Verdict.Name(proj.verdict)
    lines = [f"      verdict     {verdict}"]

    if proj.failed:
        failed = ", ".join(pb.Predicate.Name(p) for p in proj.failed)
        lines.append(f"      failed      {failed}")

    # margin is the signed distance to the nearest bound across all joints:
    # positive is headroom, negative is how far past the bound the worst joint
    # went. +inf means no joint was ordered against its bounds at all, which
    # in practice means a NaN candidate (see the note printed on that case).
    if math.isinf(proj.margin):
        lines.append(f"      margin      {proj.margin}   <-- no joint compared against its bound")
    else:
        sense = "headroom" if proj.margin >= 0 else "past the bound"
        lines.append(f"      margin      {proj.margin:+.4f} Nm ({sense})")

    lines.append(f"      candidate   {[round(v, 4) for v in proj.candidate]}")
    lines.append(f"      emitted     {[round(v, 4) for v in proj.emitted]}")
    return lines


def describe_transfer(event) -> list[str]:
    tr = event.transfer
    lines = [
        f"      {pb.Band.Name(tr.from_band)} -> {pb.Band.Name(tr.to_band)}",
        f"      trigger     {tr.trigger}",
    ]
    if tr.to_node:
        lines.append(f"      to_node     {tr.to_node}")
    if tr.recovery_ref:
        lines.append(f"      recovery    {tr.recovery_ref}")
    if tr.preempted_band_a:
        lines.append("      preempted an in-flight Band A recovery")
    return lines


def describe_event(event) -> list[str]:
    mechanism = pb.Mechanism.Name(event.mechanism)
    head = f"  [seq {event.seq:>5}] {mechanism}"
    if event.dropped_since_last:
        head += f"   (!! {event.dropped_since_last} event(s) dropped since the last one)"
    lines = [head]

    body = event.WhichOneof("body")
    if body == "projection":
        lines += describe_projection(event)
    elif body == "transfer":
        lines += describe_transfer(event)
    elif body == "isolation":
        iso = event.isolation
        lines.append(
            f"      inference   {iso.inference_ms:.3f} ms against a "
            f"{iso.wcet_budget_ms:.3f} ms budget"
            + ("   OVERRUN" if iso.compute_overrun else "")
        )
    elif body == "critic":
        cr = event.critic
        lines.append(f"      critic      {cr.critic_id} / {cr.evidence_class}")
        lines.append(f"      confidence  {cr.confidence:.3f}")
    elif body == "reentry":
        re_ = event.reentry
        verdict = "PASS" if re_.predicate_result else f"DENIED ({re_.denied_reason})"
        lines.append(f"      reentry     {verdict}, retry {re_.retry_index}")
    return lines


# ---------------------------------------------------------------------------
# Observation
# ---------------------------------------------------------------------------


@dataclass
class Observation:
    """Everything seen since the last time the timeline was drained."""

    decisions: list = field(default_factory=list)
    events: list = field(default_factory=list)
    decode_errors: list = field(default_factory=list)


class HarnessFlow(Node):
    def __init__(self, n_joints: int = 3):
        super().__init__("harness_flow")
        self.n_joints = n_joints
        self.obs = Observation()
        self._band_seen = "NOMINAL"

        # Best-effort matches the controller's realtime publishers: a
        # RealtimePublisher drops rather than blocks when it cannot get the
        # lock, so demanding reliability here would misrepresent the transport
        # the controller actually offers.
        qos = QoSProfile(depth=200, reliability=ReliabilityPolicy.BEST_EFFORT)

        self.command_pub = self.create_publisher(
            Float64MultiArray, "/upstream_effort_controller/commands", 10
        )
        self.create_subscription(
            GateStatus, "/harness_controller/gate_status", self._on_decision, qos
        )
        self.create_subscription(
            EnforcementEvents, "/harness_controller/enforcement_events", self._on_events, qos
        )
        # Latched identity. Transient-local so this still arrives even though
        # the controller published it before this script started.
        self.info = None
        self.create_subscription(
            HarnessInfo,
            "/harness_controller/info",
            self._on_info,
            QoSProfile(
                depth=1,
                reliability=ReliabilityPolicy.RELIABLE,
                durability=DurabilityPolicy.TRANSIENT_LOCAL,
            ),
        )

    def _on_info(self, msg: HarnessInfo):
        self.info = msg

    def _on_decision(self, msg: GateStatus):
        decision = DECISION_NAMES.get(msg.decision, f"?{msg.decision}")
        band = BAND_NAMES.get(msg.band, f"?{msg.band}")
        self.obs.decisions.append((decision, band, list(msg.candidate), list(msg.emitted)))

    def _on_events(self, msg: EnforcementEvents):
        # The envelope says what the bytes are. Refusing an unexpected schema
        # beats decoding it as though nothing changed — that is the whole
        # reason the field exists.
        if msg.schema != "harness.v1.EnforcementEvent":
            self.obs.decode_errors.append(f"unexpected schema {msg.schema!r}")
            return
        if msg.encoding != "protobuf-varint-delimited":
            self.obs.decode_errors.append(f"unexpected encoding {msg.encoding!r}")
            return
        try:
            self.obs.events.extend(decode_events(bytes(msg.data)))
        except ValueError as exc:
            self.obs.decode_errors.append(str(exc))

    def publish(self, value: float):
        msg = Float64MultiArray()
        msg.data = [value] * self.n_joints
        self.command_pub.publish(msg)

    def pump(self, seconds: float):
        """Publish nothing, just let callbacks run for a while."""
        deadline = time.time() + seconds
        while time.time() < deadline:
            rclpy.spin_once(self, timeout_sec=0.02)

    def drive(self, value: float, seconds: float) -> Observation:
        """Hold `value` on the command topic for `seconds`, collecting what came back."""
        self.obs = Observation()
        deadline = time.time() + seconds
        while time.time() < deadline:
            self.publish(value)
            rclpy.spin_once(self, timeout_sec=0.02)
        return self.obs


# ---------------------------------------------------------------------------
# Narration
# ---------------------------------------------------------------------------

RULE = "=" * 78


def summarise(obs: Observation, limit: int = 6):
    if obs.decode_errors:
        print("  !! event decode errors (the ring framing and this decoder disagree):")
        for err in obs.decode_errors[:3]:
            print(f"     {err}")

    if not obs.decisions:
        print("  (no decision messages — is the controller active? check the launch terminal)")
    else:
        tally: dict[tuple[str, str], int] = {}
        for decision, band, _, _ in obs.decisions:
            tally[(decision, band)] = tally.get((decision, band), 0) + 1
        print(f"  {len(obs.decisions)} gate cycles observed:")
        for (decision, band), count in sorted(tally.items(), key=lambda kv: -kv[1]):
            meaning = decision_meaning(decision, band)
            print(f"    {count:>5} x  decision={decision:<10} band={band:<8}  {meaning}")
        _, last_band, candidate, emitted = obs.decisions[-1]
        print(f"  last cycle: candidate {[round(v, 3) for v in candidate]}")
        print(f"              emitted   {[round(v, 3) for v in emitted]}   <- reached the actuator")

    transfers = [e for e in obs.events if e.WhichOneof("body") == "transfer"]
    projections = [e for e in obs.events if e.WhichOneof("body") == "projection"]
    print(
        f"  {len(obs.events)} enforcement events decoded "
        f"({len(projections)} projection, {len(transfers)} transfer)"
    )

    # Transfers are rare and are the story; always show them in full.
    #
    # Projections: show the LAST few, not the first. The upstream controller
    # holds its previous command until a new one is published and propagates,
    # so the events at the head of a scenario window still describe the
    # PREVIOUS scenario's torque — showing those made every scenario look one
    # step behind itself.
    shown = transfers + projections[-limit:]
    for event in shown:
        for line in describe_event(event):
            print(line)

    # Cross-check the two views of the same cycle against each other. In Band B
    # they disagree, and the disagreement matters: ProjectionEvent is emitted
    # in kernel_gate.cpp BEFORE the Output block applies the band fallback, so
    # `emitted` carries the clamped projection rather than the zero that
    # actually went out. enforcement.proto defines that field as "what
    # actually reached the actuator".
    if obs.decisions and projections:
        _, band, _, actual_emitted = obs.decisions[-1]
        logged_emitted = list(projections[-1].emitted)
        if band == "BAND_B" and logged_emitted and actual_emitted:
            if any(
                abs(a - b) > 1e-9 for a, b in zip(actual_emitted, logged_emitted)
            ):
                print(
                    "  !! PROVENANCE MISMATCH: the actuator received "
                    f"{[round(v, 3) for v in actual_emitted]} but the enforcement log records "
                    f"emitted={[round(v, 3) for v in logged_emitted]}.\n"
                    "     ProjectionEvent is written before the Band B fallback is applied, so "
                    "in Band B\n     the logged `emitted` is the clamp, not the output. A "
                    "threshold derived from an\n     episode that entered Band B would be "
                    "derived from values that never reached the robot."
                )

    dropped = sum(e.dropped_since_last for e in obs.events)
    if dropped:
        print(
            f"  !! {dropped} events were dropped for want of ring space. The gate never "
            "blocked to log them — evidence is what degrades under pressure, not enforcement."
        )


def check_ready(node: HarnessFlow) -> bool:
    """Confirm the controller is publishing, and that it is not already in Band B.

    Band B is terminal, so a second run of this script against a controller
    left in Band B by the first would show nothing but zeros and read as a
    broken demo rather than as the (correct) refusal it is.
    """
    node.obs = Observation()
    node.pump(2.5)

    if not node.obs.decisions:
        print(
            "\n  No messages on /harness_controller/decision.\n"
            "  The controller is not active. Check the launch terminal, then:\n"
            "      ros2 control list_controllers\n"
            "  Both harness_controller and upstream_effort_controller should be 'active'."
        )
        return False

    bands = {band for _, band, _, _ in node.obs.decisions}
    if "BAND_B" in bands:
        print(
            "\n  The controller is ALREADY in Band B — a previous run left it there, and\n"
            "  Band B is terminal in this ABI. Everything from here would emit 0.0 and the\n"
            "  walkthrough would be meaningless. Reset it with:\n"
            "      ros2 control set_controller_state harness_controller inactive\n"
            "      ros2 control set_controller_state harness_controller active\n"
            "  (deactivate/activate rebuilds a fresh hk_handle through on_configure)"
        )
        return False

    print(f"  Controller is live and in {'/'.join(sorted(bands))}.")
    return True


@dataclass
class Scenario:
    title: str
    torque: float
    seconds: float
    setup: str
    expect: str


SCENARIOS = [
    Scenario(
        title="1. Nominal — inside the declared bound",
        torque=12.5,
        seconds=2.0,
        setup="Publishing 12.5 Nm per joint, well inside the +/-40 Nm output region.",
        expect=(
            "Every cycle should be decision=ADMIT, band=NOMINAL, with emitted exactly equal "
            "to candidate. The gate is transparent when nothing is wrong — that transparency "
            "is a requirement, not a nicety: a gate that perturbs good commands cannot be "
            "left in the loop."
        ),
    ),
    Scenario(
        title="2. Approaching the bound",
        torque=39.0,
        seconds=2.0,
        setup="Publishing 39.0 Nm — legal, but only 1 Nm of headroom left.",
        expect=(
            "Still ADMIT, but watch `margin` collapse toward zero. Margin is the signed "
            "distance to the binding bound, and it is the quantity a threshold is later "
            "derived from — which is why it is logged on admitted cycles too, not only on "
            "violations."
        ),
    ),
    Scenario(
        title="3. Violation — Projection clamps, then Band B takes authority",
        torque=250.0,
        seconds=3.0,
        setup="Publishing 250.0 Nm, far outside the region.",
        expect=(
            "Two distinct things happen, in this order, and the distinction is the whole "
            "design:\n"
            "        (a) Projection clamps IMMEDIATELY and mechanically: decision=CLAMP, "
            "emitted pinned to exactly 40.0, verdict=REPLACE, failed=[VALUE_RANGE]. This "
            "happens on every violating cycle and involves no authority change whatsoever.\n"
            "        (b) Only the RATE of violation feeds Transfer. The window looks back "
            "500 ms, which at 200 Hz is ~100 samples, and the trigger needs the violating "
            "fraction of that whole window to exceed 0.5 — so roughly 50 clamped cycles "
            "(~250 ms) of sustained violation, not 4. (kRejectRateMinSamples=4 is the "
            "minimum needed to EVALUATE the rate at all, not to trip it.) Then a TRANSFER "
            "event fires: NOMINAL -> BAND_B, trigger=projection_reject_rate.\n"
            "        After the transfer the profile's on_reject=ZERO output governs and "
            "emitted becomes 0.0 regardless of what is commanded.\n"
            "        (Set band_b_reject_rate_max to 1.0 in harness_controllers.yaml to make "
            "the trigger unreachable and watch clamping alone, indefinitely.)"
        ),
    ),
    Scenario(
        title="4. Recovery attempt — proving Band B is terminal",
        torque=5.0,
        seconds=2.0,
        setup="Dropping back to a perfectly legal 5.0 Nm after the transfer.",
        expect=(
            "emitted stays 0.0. A well-behaved command does NOT win authority back. To "
            "recover, deactivate and reactivate the controller (which builds a fresh "
            "hk_handle via on_configure):\n"
            "      ros2 control set_controller_state harness_controller inactive\n"
            "      ros2 control set_controller_state harness_controller active"
        ),
    ),
]


def run_walkthrough(node: HarnessFlow, auto: bool):
    print(RULE)
    print("harness controller — flow of enforcement")
    print(RULE)
    print(
        "\nTopology: you publish to /upstream_effort_controller/commands; that controller\n"
        "writes into harness_controller's exported reference interfaces; harness_controller\n"
        "runs hk_gate and writes the GATED effort to the hardware. Nothing reaches the\n"
        "effort interface except through the gate — controller_manager's resource manager\n"
        "enforces that exclusivity, so it is not a matter of convention.\n"
    )

    print("Waiting for the controller's publishers…")
    if not check_ready(node):
        return

    for scenario in SCENARIOS:
        print()
        print(RULE)
        print(scenario.title)
        print(RULE)
        print(f"  setup:  {scenario.setup}")
        print(f"  expect: {scenario.expect}")
        if not auto:
            try:
                input("\n  [Enter] to run this scenario, Ctrl-C to stop… ")
            except (EOFError, KeyboardInterrupt):
                print("\nstopped.")
                return
        print()
        obs = node.drive(scenario.torque, scenario.seconds)
        summarise(obs)

    print()
    print(RULE)
    print("Walkthrough complete.")
    print(RULE)
    print(
        "\nOne thing this demo cannot show, deliberately: a NaN command. hk_gate has no\n"
        "finiteness predicate — margin = min(NaN, NaN) is NaN, and NaN < 0.0 is false — so a\n"
        "NaN is ADMITted unclamped, cached as last_admitted, and logged with margin=+inf.\n"
        "See test_gate_loop.cpp::nan_reference_is_admitted_ungated, which pins that gap.\n"
        "Try it with --repl and enter 'nan' if you want to watch it happen.\n"
    )


def run_repl(node: HarnessFlow):
    print(RULE)
    print("harness controller — interactive mode")
    print(RULE)
    print(
        "\nEnter a torque in Nm to command on every joint, and watch what the gate does\n"
        "with it. The declared output region is +/-40 Nm.\n"
        "  try:  5      admitted unchanged\n"
        "        39.9   admitted, almost no margin\n"
        "        60     clamped to 40\n"
        "        nan    admitted ungated — the missing finiteness predicate\n"
        "        inf    clamped, because infinities ARE ordered against the bounds\n"
        "  'q' to quit.\n"
    )
    if not check_ready(node):
        return

    while True:
        try:
            raw = input("torque (Nm) > ").strip()
        except (EOFError, KeyboardInterrupt):
            print()
            return
        if raw.lower() in {"q", "quit", "exit"}:
            return
        if not raw:
            continue
        try:
            value = float(raw)  # accepts 'nan' and 'inf' by design
        except ValueError:
            print("  not a number. try 5, 60, nan, inf, or q")
            continue

        obs = node.drive(value, 1.0)
        summarise(obs, limit=2)
        print()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--auto", action="store_true", help="run the walkthrough without waiting for Enter"
    )
    parser.add_argument(
        "--repl", action="store_true", help="type torque values and watch the gate respond"
    )
    parser.add_argument("--joints", type=int, default=3, help="number of gated joints")
    args = parser.parse_args()

    rclpy.init()
    node = HarnessFlow(n_joints=args.joints)
    try:
        if args.repl:
            run_repl(node)
        else:
            run_walkthrough(node, auto=args.auto)
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == "__main__":
    main()
